name: "S3 Upload - Async action"
description: "Upload files and directories to S3 compatible cloud buckets"
author: "DemaTrading.ai <contact@dematrading.ai>"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: message-square
  color: gray-dark
