name: "S3 Upload - V4 Signature"
description: "Upload files and directories to S3 compatible cloud buckets"
author: "DemaTrading.ai <contact@dematrading.ai>"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: message-square
  color: gray-dark
